FILE =	megaphone.cpp

NAME = megaphone

COMPILE = clang++ $(FLAGS)

FLAGS = -Wall -Wextra -Werror

all: $(NAME)


$(NAME):

	$(COMPILE) $(FILE) -o $(NAME)

clean:
	
fclean : clean
		rm -rf $(NAME)

re: fclean all
